[package]
name = "vfeeder-config"
version = "1.0.0"
description = "vFeeder Config - ESP32 Configuration Tool"
authors = ["vienkmt"]
edition = "2021"

[lib]
name = "vfeeder_config_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serialport = "4.3"
parking_lot = "0.12"
